apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mn
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: "pv0001"